[package]
name = "xamltoolkit-rs"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"
autoexamples = false

[workspace]
members = [
    "wasdk",
    "xamltoolkit-winui",
    "xamltoolkit-winui-converters",
    "xamltoolkit-winui-helpers",
    "xamltoolkit-winui-controls",
]
resolver = "2"

[workspace.dependencies]
windows-bindgen = "0.100"
windows-collections = "0.100"
windows-core = "0.100"
windows-future = "0.100"
windows-metadata = "0.100"
windows-numerics = "0.100"
windows-reference = "0.100"
windows-time = "0.100"

[dependencies]
wasdk = { path = "wasdk" }
toolkit-winui = { path = "xamltoolkit-winui" }
toolkit-winui-converters = { path = "xamltoolkit-winui-converters" }
toolkit-winui-helpers = { path = "xamltoolkit-winui-helpers" }
toolkit-winui-controls = { path = "xamltoolkit-winui-controls" }
windows-core = { workspace = true }

[[example]]
name = "root"
path = "examples/root.rs"

[[example]]
name = "converters"
path = "examples/converters.rs"

[[example]]
name = "helpers"
path = "examples/helpers.rs"

[[example]]
name = "controls"
path = "examples/controls.rs"
